services:

  postgres:
    container_name: postgres
    image: postgres:16.4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    container_name: app
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - backdata:/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env

volumes:
  postgres:
  backdata:

networks:
  default: